apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming-app
  labels:
    app: video-streaming-app
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: video-streaming-app
  template:
    metadata:
      labels:
        app: video-streaming-app
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: video-service
          image: video-streaming:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "info"
            - name: RATE_LIMIT_MAX_REQUESTS
              value: "10000"  # High limit for load testing
            - name: RATE_LIMIT_WINDOW_MS
              value: "60000"   # 1 minute window
          resources:
            requests:
              cpu: "100m"   # Reduced for more pods
              memory: "128Mi" # Reduced for more pods
            limits:
              cpu: "1000m"   # Sufficient for load testing
              memory: "256Mi" # Reduced to fit more pods
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: tmp
          emptyDir: {}
        - name: uploads
          emptyDir:
            sizeLimit: 1Gi
