apiVersion: v1
kind: Service
metadata:
  name: video-demo-svc
  labels:
    app: video-demo
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: LoadBalancer
  selector:
    app: video-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None
